import type { Metadata } from "next";
import "./globals.css";
import SidebarNavigation from "@/components/sidebar/Navigation";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="flex flex-col h-screen">
        <Header />
        <SidebarNavigation />
        {children}
      </body>
    </html>
  );
}
